Enable setting debug values via env vars
bratpiorka/memkind_hot_poc pull request #3
Opened 2021-10-08 09:46 UTC by PatKamin

Parse 4 new environment variables:
- SAMPLE_FREQUENCY
- PEBS_FREQ_HZ
- HOTNESS_MEASURE_WINDOW
- OLD_TIME_WINDOW_HOTNESS_WEIGHT

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/3)

2021-10-11 13:07 UTC, maciekpac commented on include/memkind/internal/memkind_memtier.h
> +extern float pebs_freq_hz;
Why float? Unless vectorized or memory-bound, double operations should be as fast as float operations, with minimal memory overhead.

2021-10-11 13:08 UTC, maciekpac commented on include/memkind/internal/memkind_memtier.h
> +extern float old_time_window_hotness_weight;
ditto - float vs double

2021-10-11 13:08 UTC, maciekpac commented on src/memkind_memtier.c
> +    float pebs_freq_hz;
ditto: float vs double

2021-10-11 13:10 UTC, maciekpac commented on src/memkind_memtier.c
> +        pebs_freq_hz = strtof(env_var, NULL);
Check for zero - if zero is supplied, segfault appears in pebs.c, line 82

2021-10-11 13:12 UTC, maciekpac commented on src/memkind_memtier.c
> +        pebs_freq_hz = strtof(env_var, NULL);
check that value > 0; otherwise, calculations and units do not make sense

2021-10-11 13:13 UTC, maciekpac commented on src/memkind_memtier.c
> +    unsigned long sample_frequency;
This should be a float/double - we might want to test lower frequencies, e.g. 0.5 Hz or 0.1 Hz as well.

Please remember about adding some basic checks

2021-10-15 10:48 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/3)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @bratpiorka, @maciekpac, and @PatKamin)

___
*[src/memkind_memtier.c, line 813 at r1](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/3#-MlUPuV-d1KaAryH4vEH-r1-813:-Mm2ZJV_2lANyv01tTpf:b-896fix) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/a8ccafb5bb0f676b70e1b7aab311c84dab11a722/src/memkind_memtier.c#L813)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

check that value > 0; otherwise, calculations and units do not make sense
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-15 11:42 UTC, bratpiorka approved these changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/3)* status: all files reviewed, 5 unresolved discussions (waiting on @maciekpac)



<!-- Sent from Reviewable.io -->

2021-10-19 10:22 UTC, bratpiorka requested changes
> Reviewed 3 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/3)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @bratpiorka, @maciekpac, and @PatKamin)

___
*[src/ranking.cpp, line 506 at r5](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/3#-MmN3eH720nQQKDFq6g0:-MmN3eH720nQQKDFq6g1:b-389tr1) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/61e1cf3366288f23f2d1a2ece68a0b577dcfbcba/src/ranking.cpp#L506)):*
> ```cpp
> //                                     const struct ttype *updated_values)
> // {
> //     ranking_remove_internal(ranking, entry_to_update);
> ```

why this is changed? is it a mistake?


<!-- Sent from Reviewable.io -->

2021-10-19 10:25 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/3)* status: all files reviewed, 5 unresolved discussions (waiting on @maciekpac)

___
*[src/ranking.cpp, line 506 at r5](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/3#-MmN3eH720nQQKDFq6g0:-MmN4I9-7cgbOXK3f_U3:b-1c0456) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/61e1cf3366288f23f2d1a2ece68a0b577dcfbcba/src/ranking.cpp#L506)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

why this is changed? is it a mistake?
</blockquote></details>

There is no change here against the master branch.


<!-- Sent from Reviewable.io -->

2021-10-19 14:21 UTC, merged