Tweak tests viz temp debug
bratpiorka/memkind_hot_poc pull request #36
Opened 2022-01-21 07:03 UTC by PatKamin

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

2022-01-21 09:18 UTC, bratpiorka reviewed
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)



<!-- Sent from Reviewable.io -->

2022-01-24 10:10 UTC, bratpiorka requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 148 at r3](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36#-MuAZ8FgAI3sOJM5FKMm:-MuAZ8FgAI3sOJM5FKMn:bale5ew) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/57c2cea70ae185645a086fa50dfe83f113e8b72e/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L148)):*
> ```cpp
>         const size_t data_size_u64 = dataSize/sizeof(uint64_t);
>         for (size_t it=0; it<iterations; ++it)
>             for (size_t i=0; i<dataSize/sizeof(uint64_t); i += CACHE_LINE_SIZE_U64) {
> ```

why not data_size_u64? here and in all test scenarios?


<!-- Sent from Reviewable.io -->

2022-01-28 13:26 UTC, maciekpac requested changes
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36)* status: all files reviewed, 17 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[parse_heatmap.py, line 90 at r3](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36#-MuVotYY5GXf1FIsjd2e:-MuVotYY5GXf1FIsjd2f:b-7y0eo4) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/57c2cea70ae185645a086fa50dfe83f113e8b72e/parse_heatmap.py#L90)):*
> ```Python
>     ax[0].set_xlabel('type index')
>     ax[1].set_xlabel('type index')
>     ax[0].set_ylabel('hotness (normalixed)')
> ```

typo
normalixed -> normalized
___
*[parse_heatmap.py, line 94 at r3](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36#-MuVoznb6IscdraENdwH:-MuVoznb6IscdraENdwI:b-7ropln) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/57c2cea70ae185645a086fa50dfe83f113e8b72e/parse_heatmap.py#L94)):*
> ```Python
>     ax[1].set_title('Dram to total')
>     ax[0].set_xlabel('type index')
>     ax[0].set_ylabel('hotness (normalixed)')
> ```

ditto
___
*[parse_heatmap.py, line 104 at r3](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36#-MuVp0Ol78pUs3WWafL0:-MuVp0Ol78pUs3WWafL1:b-7ropln) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/57c2cea70ae185645a086fa50dfe83f113e8b72e/parse_heatmap.py#L104)):*
> ```Python
>     ax[0].set_title('Hotness')
>     ax[0].set_xlabel('type index')
>     ax[0].set_ylabel('hotness (normalixed)')
> ```

ditto
___
*[parse_heatmap.py, line 108 at r3](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36#-MuVp1Qi3Cysy-zynE-g:-MuVp1Qi3Cysy-zynE-h:b-7ropln) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/57c2cea70ae185645a086fa50dfe83f113e8b72e/parse_heatmap.py#L108)):*
> ```Python
>     ax[1].set_title('Dram to total')
>     ax[0].set_xlabel('type index')
>     ax[0].set_ylabel('hotness (normalixed)')
> ```

ditto
___
*[Requirements.txt, line 2 at r3](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36#-MuVpAvJ3gKZX4TZyM7y:-MuVpAvJ3gKZX4TZyM7z:bxsbuh1) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/57c2cea70ae185645a086fa50dfe83f113e8b72e/Requirements.txt#L2)):*
> ```help
> numpy
> pandas
> ```

Actually, do we use it anywhere ?
___
*[include/memkind/internal/memkind_memtier.h, line 364 at r3](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36#-MuVpIGa-SL0qxUfAX-2:-MuVpIGa-SL0qxUfAX-3:b-hd2llx) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/57c2cea70ae185645a086fa50dfe83f113e8b72e/include/memkind/internal/memkind_memtier.h#L364)):*
> ```objc
> 
> // static const double EXPONENTIAL_COEFFS_VALS[] = { 0.9, 0.99, 0.999, 0.9999};
> static const double EXPONENTIAL_COEFFS_VALS[] = { 1, 1, 1, 1};
> ```

This was added only for debugging, the line above should be restored
___
*[src/bigary.c, line 10 at r3](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36#-MuVpYXu4aE6rVSrLiQE:-MuVpYXu4aE6rVSrLiQF:b-xvbsib) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/57c2cea70ae185645a086fa50dfe83f113e8b72e/src/bigary.c#L10)):*
> ```C
> 
> #include "memkind/internal/bigary.h"
> // default max: 16 GB
> ```

outdated
___
*[src/bigary.c, line 11 at r3](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36#-MuVpPTs-eqEjG8F_AJt:-MuVpPTs-eqEjG8F_AJu:b-nrtztl) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/57c2cea70ae185645a086fa50dfe83f113e8b72e/src/bigary.c#L11)):*
> ```C
> #include "memkind/internal/bigary.h"
> // default max: 16 GB
> // #define BIGARY_DEFAULT_MAX (16 * 1024 * 1024 * 1024ULL)
> ```

remove the commented out code
___
*[src/memkind_memtier.c, line 478 at r3](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36#-MuVpiadEYmS4WWKJvC4:-MuVpiadEYmS4WWKJvC5:bxjxptv) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/57c2cea70ae185645a086fa50dfe83f113e8b72e/src/memkind_memtier.c#L478)):*
> ```C
> }
> 
> MEMKIND_EXPORT void print_memtier_memory(struct memtier_memory *memory)
> ```

side note: I think that we would need to have another macro, e.g. MEMKIND_TEST to expose more functions to unit tests, while hiding them from client libraries.. But you don't need to modify anything here
___
*[src/pebs.c, line 452 at r3](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36#-MuVq2z_3KorXZAnBiK4:-MuVq2zaEkfaVyV0LxmE:b-y8aqqo) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/57c2cea70ae185645a086fa50dfe83f113e8b72e/src/pebs.c#L452)):*
> ```C
>     pe.precise_ip = 2; // NOTE: this is reqired but was not set
>                        // by pfm_get_os_event_encoding()
> //     pe.read_format = PERF_FORMAT_ID;
> ```

remove unused code
___
*[src/pebs.c, line 466 at r3](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36#-MuVq5fR6avXSl3YArDj:-MuVq5fR6avXSl3YArDk:b-y8aqqo) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/57c2cea70ae185645a086fa50dfe83f113e8b72e/src/pebs.c#L466)):*
> ```C
> 
>     int group_fd = -1;          // use single event group
> //     int group_fd = 0;
> ```

remove unused code
___
*[utils/memtier_zipf_bench/Makefile.mk, line 11 at r3](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36#-MuVqNC-ElTxoNMUxHXZ:-MuVqNC-ElTxoNMUxHX_:b-y8aqqo) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/57c2cea70ae185645a086fa50dfe83f113e8b72e/utils/memtier_zipf_bench/Makefile.mk#L11)):*
> ```Makefile
> utils_memtier_zipf_bench_memtier_zipf_bench_LDADD = libmemkind.la
> utils_memtier_zipf_bench_memtier_zipf_bench_LDFLAGS = $(PTHREAD_CFLAGS)
> # utils_memtier_zipf_bench_memtier_zipf_bench_CXXFLAGS = "$(utils_memtier_zipf_bench_memtier_zipf_bench_CXXFLAGS) -DLEVEL1_DCACHE_LINESIZE
> ```

remove unused code



_Code quote:_
```Makefile
# utils_memtier_zipf_bench_memtier_zipf_bench_CXXFLAGS = "$(utils_memtier_zipf_bench_memtier_zipf_bench_CXXFLAGS) -DLEVEL1_DCACHE_LINESIZE
# utils_memtier_zipf_bench_memtier_zipf_bench_CXXFLAGS = "-DCACHE_LINE_SIZE_U64=\"`getconf LEVEL1_DCACHE_LINESIZE`\" -std=c++20"
```
___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 148 at r3](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36#-MuAZ8FgAI3sOJM5FKMm:-MuVqYaTB2R3Rxuw1f2_:b32wyo) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/57c2cea70ae185645a086fa50dfe83f113e8b72e/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L148)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

why not data_size_u64? here and in all test scenarios?
</blockquote></details>

up
___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 194 at r3](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36#-MuVqagcDyc1g49NEHxi:-MuVqagcDyc1g49NEHxj:b-y8aqqo) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/57c2cea70ae185645a086fa50dfe83f113e8b72e/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L194)):*
> ```cpp
>         assert(!this_thread);
>         this_thread = std::make_shared<std::thread>([this, fence](){
> //             std::this_thread::sleep_for(std::chrono::seconds(10));
> ```

remove unused code
___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 214 at r3](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36#-MuVqhYM3C5pgne9pxsV:-MuVqhYM3C5pgne9pxsW:b-5ur4j8) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/57c2cea70ae185645a086fa50dfe83f113e8b72e/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L214)):*
> ```cpp
> 
> #if IS_TEST_ACCESS_RANDOM
> std::random_device Loader::dev;
> ```

maybe we should check performance with multiple local random devices? 
___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 381 at r3](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36#-MuVqyes05EU-4Ui1yUh:-MuVqyes05EU-4Ui1yUi:b-tp3683) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/57c2cea70ae185645a086fa50dfe83f113e8b72e/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L381)):*
> ``` [...]

2022-01-28 13:29 UTC, maciekpac requested changes
The temp_debug branch originally was not meant to be merged... it contains a lot of debug code and requires a lot of cleaning :/

> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36#-:-MuVrxiy9nCsqrAyGzPc:brtty0w)* status: all files reviewed, 19 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[include/memkind/internal/memkind_memtier.h, line 300 at r3](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36#-MuVr_oNDPOA739PvKXe:-MuVr_oNDPOA739PvKXf:b-z9px0i) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/57c2cea70ae185645a086fa50dfe83f113e8b72e/include/memkind/internal/memkind_memtier.h#L300)):*
> ```objc
> 
> 
> #define PRINT_MEMDUMP_INTERVAL 15
> ```

This value generates a lot of dumps under some scenarios... Should it stay like that.
___
*[include/memkind/internal/memkind_memtier.h, line 361 at r3](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/36#-MuVrlVpCB7-rDjma04x:-MuVrlVpCB7-rDjma04y:b-rjb42v) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/57c2cea70ae185645a086fa50dfe83f113e8b72e/include/memkind/internal/memkind_memtier.h#L361)):*
> ```objc
> #define HOTNESS_INITIAL_SINGLE_VALUE 0.0
> /// touch value: its significance is limited to preventing buffer overflow
> #define HOTNESS_TOUCH_SINGLE_VALUE 1e9
> ```

not sure if this value should stay like that, we might stumble upon double overflow issues


<!-- Sent from Reviewable.io -->

2022-02-09 13:20 UTC, closed without merging